import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { Toaster } from "sonner";

import "./globals.css";
import { TRPCProvider } from "@/src/trpc/client";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
    <html lang="en">
      <body
        className={inter.className}
      >
      <TRPCProvider> 
        <Toaster /> 
        {children}
      </TRPCProvider>  
      </body>
    </html>
    </ClerkProvider>
  );
};
